config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount Sidekiq::Web => '/sidekiq'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "static_pages#home"
  get 'static_pages/home', to: 'static_pages#home'
  get 'static_pages/secret', to: 'static_pages#secret'

  resources :movies do
    collection do
      get :omdb_search
      post :omdb_import
    end

    resources :comments, only: %i[create edit update destroy]
  end

  resource :profile, only: %i[edit update], controller: :profiles
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: %i[show edit update destroy]

  # GET /movies
  def index
    @movies = Movie.all
  end

  # GET /movies/:id
  def show
    @omdb = OmdbClient.new
    @omdb_movie = @omdb.find_by_title(@movie.title)
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # POST /movies
  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      flash[:notice] = 'Movie created'
      redirect_to @movie
    else
      flash[:alert] = @movie.errors.full_messages.join(", ")
      redirect_to new_movie_path
    end
  end

  # GET /movies/:id/edit
  def edit
  end

  # PUT/PATCH /movies/:id
  def update
    @movie.assign_attributes(movie_params)
    if @movie.save
      redirect_to @movie
    else
      flash.now[:alert] = @movie.errors.full_messages.join(", ")
      redirect_to @movie 
    end
  end

  # DELETE /movies/:id
  def destroy
    @movie.destroy!
    
    respond_to do |format|
      format.html { redirect_to movies_path, flash: 'Movie destroyed' }
      format.json { head :no_content }
    end
  end


  def omdb_search
    if params[:search_query].present?
      @omdb = OmdbClient.new

      # @search_results = @omdb.search(params[:search_query])['Search']
      res = @omdb.search(params[:search_query])
      @search_results = res['Search']
    end
  end

  def omdb_import
    # @omdb = OmdbClient.new

    # @omdb_movie = @omdb.find_by_id(params[:omdb_id])

    # @movie = Movie.new(
    #   title: @omdb_movie['Title'],
    #   cover_image_url: @omdb_movie['Poster'],
    #   year_of_creation: @omdb_movie['Year'],
    #   description: @omdb_movie['Plot'],
    #   duration: @omdb_movie['Runtime'],
    #   director: @omdb_movie['Director'],
    #   genres: @omdb_movie['Genre'].split(', ')
    # )
    # if @movie.save
    #   redirect_to @movie
    # else
    #   flash[:alert] = @movie.errors.full_messages.join(", ")
    #   redirect_to omdb_search_movies_path
    # end

    MoviesImportJob.perform_later(params[:omdb_id], current_user)
    flash[:notice] = 'Movie will be imported soon. Thanks!'
    redirect_to movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :description, :duration, :director, :year_of_creation, :cover_image_url, genres: [])
  end

  def find_movie
    @movie = Movie.find(params[:id])
  end
end

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<%= render 'movies/shared/form', movie: @movie %>

app/views/movies/index.html.erb
<h1>All Movies</h1>

<% @movies.each do |movie| %>
  <% if movie.cover_image_url %>
    <h2><%= image_tag(movie.cover_image_url) %></h2>
  <% end %>
  <h2>Title: <%= link_to(movie.title, movie_path(movie)) %></h2>
  <h3>Description <%= movie.description %></h3>
  <p>Year of Creation: <%= movie.year_of_creation %></p>
  <p>Genre: <%= movie.genres %></p>
  <p>Director: <%= movie.director %></p>
<% end %>

app/views/movies/new.html.erb
<h1>New Project</h1>

<%= render 'movies/shared/form', movie: @movie %>

app/views/movies/omdb_search.html.erb
<h1>Omdb search</h1>
<%= form_tag omdb_search_movies_path, method: :get do %>
  <div style='margin-bottom: 10px;'>
    <%= label_tag :search_query %>
    <%= text_field_tag :search_query, params[:search_query] %>
  </div>

  <%= submit_tag 'Search' %>
<% end %>

<% if @search_results.present? %>
  <table>
    <thead>
      <th>Title</th>
      <th>Year</th>
      <th>Image</th>
      <th>Actions</th>
    </thead>
    <tbody>
    <% @search_results.each do |movie| %>
      <tr>
        <td><%= movie['Title'] %></td>
        <td><%= movie['Year'] %></td>
        <td>
          <% begin %>
            <%= image_tag(movie['Poster']) %>
          <% rescue Sprockets::Rails::Helper::AssetNotFound %>
            <%= image_tag('test_image.png') %>
            <p>No image</p>
          <% rescue StandardError %>
            <p>Custom error</p>
          <%end%>
        </td>
        <td>
          <%= form_tag omdb_import_movies_path(omdb_id: movie['imdbID']), 
                        method: :post do %>
            <%= submit_tag 'Import' %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/movies/show.html.erb
<h1>Show view</h1>
<% if @movie.cover_image_url %>
  <h2><%= image_tag(@movie.cover_image_url) %></h2>
<% end %>
<h2>Title: <%= @movie.title %></h2>
<h3>Description <%= @movie.description %></h3>
<p>Year of Creation: <%= @movie.year_of_creation %></p>
<p>Genre: <%= @movie.genres.filter_map { |g| g.titleize if g.present? }.join(', ') %></p>
<p>Director: <%= @movie.director %></p>
<%= link_to('EDit', edit_movie_path(@movie)) %>

<hr/>

<hr/>

<% @movie.comments.includes(:user).each do |comment| %>
  <%= turbo_frame_tag(dom_id(comment)) do %>
    <p>
      <%= comment.body %> (by <%= comment.user.email %>)
      <% if policy(comment).edit? %>
        <%= link_to('edit', edit_movie_comment_path(comment, movie_id: comment.commentable.id)) %>
      <% end %>

      <% if policy(comment).destroy? %>
        <%= link_to('destroy',
                    movie_comment_path(comment, movie_id: comment.commentable),
                    data: { turbo_method: :delete }) %>
      <% end %>
      <div class='container-50'>
        <% comment.comments.includes(:user).each do |sub_comment| %>
          <%= sub_comment.body %> (replay by <%= sub_comment.user.email %>)
          <br/>
        <% end %>
        <%= render partial: 'comments/form', locals: { comment_to: comment } %>
      </div>
    </p>
  <% end %>
<% end %>

<%= render partial: 'comments/form', locals: { comment_to: @movie } %>